"""MonoMech public API."""

from .animation import (
    OpenSimAnimationResult,
    OpenSimVisualizerResult,
    create_glb_viewer,
    display_visualizer,
    extract_opensim_marker_positions,
    glb_viewer,
    save_animation_viewer,
    save_ik_animation,
    save_opensim_animation,
    save_opensim_fast_visualizer,
    save_opensim_glb,
    save_opensim_visualizer,
    show_ik_animation,
)
from .api import (
    animate,
    estimate_grf,
    estimate_pose,
    external_forces,
    fast_viewer,
    gap_fill,
    load,
    marker_pipeline,
    run_id,
    run_ik,
    run_scaling,
    smooth,
    video_pipeline,
)
from .config import (
    ButterworthConfig,
    GapFillConfig,
    OpenSimIDConfig,
    OpenSimIKConfig,
    OpenSimScaleConfig,
    Pose2DConfig,
    Pose3DGlobalConfig,
    Pose3DWorldConfig,
)
from .core.study import Study
from .core.trials import BaseTrial, MarkerTrial, VideoTrial
from .external import ExternalLoadsSpec, external
from .io.model import build_marker_map, inspect_model_markers
from .io.trc import load_marker_dataframe, load_trc
from .io.video import load_video, load_videos
from .pipeline import (
    InverseDynamicsPipelineResult,
    MarkerToIDResult,
    VideoInverseDynamicsResult,
    VideoToIDResult,
    estimate_loads_from_pose,
    load_trc_to_id,
    markers_to_id,
    pose_to_trc,
    trc_to_id,
    trc_to_inverse_dynamics,
    video_to_id,
    video_to_inverse_dynamics,
    video_to_trc,
)
from .resources import (
    builtin_osim_model_path,
    builtin_pose_model_path,
    get_builtin_geometry_dir,
    get_builtin_osim_model,
    list_builtin_osim_models,
)
from .viz import install_plot_methods

install_plot_methods()

__all__ = [
    "BaseTrial",
    "VideoTrial",
    "MarkerTrial",
    "Study",
    "ExternalLoadsSpec",
    "InverseDynamicsPipelineResult",
    "VideoInverseDynamicsResult",
    "MarkerToIDResult",
    "VideoToIDResult",
    "external",
    "estimate_pose",
    "smooth",
    "gap_fill",
    "run_scaling",
    "run_ik",
    "load",
    "estimate_grf",
    "external_forces",
    "fast_viewer",
    "run_id",
    "animate",
    "video_pipeline",
    "marker_pipeline",
    "video_to_trc",
    "trc_to_inverse_dynamics",
    "video_to_inverse_dynamics",
    "pose_to_trc",
    "markers_to_id",
    "trc_to_id",
    "load_trc_to_id",
    "video_to_id",
    "estimate_loads_from_pose",
    "OpenSimAnimationResult",
    "OpenSimVisualizerResult",
    "create_glb_viewer",
    "glb_viewer",
    "display_visualizer",
    "extract_opensim_marker_positions",
    "save_opensim_animation",
    "save_opensim_glb",
    "save_opensim_fast_visualizer",
    "save_opensim_visualizer",
    "save_ik_animation",
    "save_animation_viewer",
    "show_ik_animation",
    "load_video",
    "load_videos",
    "load_trc",
    "load_marker_dataframe",
    "inspect_model_markers",
    "build_marker_map",
    "Pose2DConfig",
    "Pose3DWorldConfig",
    "Pose3DGlobalConfig",
    "OpenSimScaleConfig",
    "OpenSimIKConfig",
    "OpenSimIDConfig",
    "ButterworthConfig",
    "GapFillConfig",
    "builtin_osim_model_path",
    "builtin_pose_model_path",
    "get_builtin_geometry_dir",
    "builtin_osim_model_path",
    "builtin_pose_model_path",
    "get_builtin_osim_model",
    "list_builtin_osim_models",
]
